# 指定具体包的日志级别
logging:
  config: classpath:logback-spring.xml
  level:
    com.example.javamaildemo: debug
server:
  port: 6001
  # 拼接请求-路径前缀
  servlet:
#    context-path: /java-dev-demo
spring:
  mail:
    host: smtp.163.com
    username: song5_wang@163.com
    password: FIUECJDZXERBYFNZ
  redis:
    # 数据库索引 默认是0
    database: 0
    # Redis服务器地址
    host: 192.168.170.181
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://database.coding-future.com:3306/postgres
  #    username: erp_220504_one
  #    password: 123456
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.170.181:5432/ws_test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: postgres
    password: 123456
#    password: ws810216

#    dynamic:
#      primary: master
#      datasource:
#        master:
#          driver-class-name: org.postgresql.Driver
#          url: jdbc:postgresql://localhost:5432/postgres?currentSchema=wstest&characterEncoding=utf-8&serverTimezone=GMT%2B8
#          username: postgres
#          password: postgres
#        slave_1:
#          driver-class-name: org.postgresql.Driver
#          url: jdbc:postgresql://localhost:5432/postgres?currentSchema=wstest&characterEncoding=utf-8&serverTimezone=GMT%2B8
#          username: postgres
#          password: postgres
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 全局配置，也可以通过配置类来配置 public GlobalConfig globalConfig() { return new GlobalConfig(); }
  global-config:
    db-config:
      # 拼接sql时会加上前缀t_: select t_person
      table-prefix: t_
#      id-type: input

wx_app_id: wxed9954c01bb89b47
wx.open.app_secret: a7482517235173ddb4083788de60b90e
wx.open.redirect_url: wxed9954c01bb89b47

